---
name: Checkov

on:
  push:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
